# Generated by Django 3.2.7 on 2021-09-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degradation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gas_capacity', models.FloatField()),
                ('gas_count', models.FloatField()),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_maintenance.tyre')),
            ],
        ),
    ]
