# Generated by Django 3.2.7 on 2021-09-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tyre',
        ),
        migrations.AddField(
            model_name='tyre',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car_maintenance.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='gas_capacity',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='gas_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='degradation',
            field=models.FloatField(default=0),
        ),
    ]
