# Generated by Django 3.2.7 on 2021-09-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance', '0002_auto_20210904_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gas_count',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyres', to='car_maintenance.car'),
        ),
    ]
