# Generated by Django 3.2.7 on 2021-09-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance', '0003_auto_20210904_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('distance_travelled', models.FloatField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
