# Generated by Django 3.2.7 on 2021-09-05 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car_maintenance.car'),
            preserve_default=False,
        ),
    ]
