# Generated by Django 3.2.7 on 2021-09-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance', '0008_auto_20210906_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gas_amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to='car_maintenance.car')),
            ],
        ),
    ]
